### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by ChristianGiupponi** [andreapollastri/easydock#2]
Hi,  
I'm trying to use easydock for my docker development env but I'm found out some missing libraries required for some of my projects.  
Here what seems to missing in the php installation:

- GD library
- IMAP library

![Schermata 2021-01-21 alle 10 01 16](https://user-images.githubusercontent.com/1614796/105327947-d122aa80-5bcf-11eb-923b-a7c477b5d707.png)
![Schermata 2021-01-21 alle 10 01 20](https://user-images.githubusercontent.com/1614796/105327950-d253d780-5bcf-11eb-97fe-2caf2acaaf75.png)

This is my php configuration in `.env`:

```
# PHP VERSION (7.2 / 7.3 / 7.4)
PHP_V=7.3
```

Seems that this peace of scripts is failing somehow

```
RUN if [ ${PHP_V} < 7.4 ] ; then \
    docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ \
    && docker-php-ext-install gd;\
fi;
```

**Comment by andreapollastri** [comment]
Thank you for the issue Christian... I'll investigate and fix it!

**Comment by andreapollastri** [comment]
I fixed it... let me know if it works! ;)
