### ISSUE TITLE
Forking Easydock for Linux

### ISSUE THREAD

**Issue by joglomedia** [andreapollastri/easydock#26]
Hi Andrea,

I am really excited with your easydock tool, however as Linux (Ubuntu) user I try to fork and enhance your works so it compatible for Linux environment and also add some additional features there

Please see my version here https://github.com/joglomedia/easydock-linux

If you found it is useful or have any suggestion please let me know :)

Regards

**Comment by andreapollastri** [comment]
Hi, thank you for the interest. I don't use Linux but I'll check your version soon and I will let you know what I think about it. In the meanwhile Thank You.
